In [2]:
import numpy as np

In [31]:
#task1
arr = np.arange(1,21)
print("1-D: ", arr)
rearr = arr.reshape((4,5))
print("Re-shaped: ", rearr)
rearr[:,4] = 0
print("Last column zero: ", rearr)
flat = rearr.reshape(-1)
print("Flattened Array: ", flat)

1-D:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Re-shaped:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Last column zero:  [[ 1  2  3  4  0]
 [ 6  7  8  9  0]
 [11 12 13 14  0]
 [16 17 18 19  0]]
Flattened Array:  [ 1  2  3  4  0  6  7  8  9  0 11 12 13 14  0 16 17 18 19  0]


In [60]:
#task2
arr = np.random.randint(low=1, high=51, size=(5,5))
print("Random array: ", arr)

for i in range (len(arr)):
    print(f"Mean for row {i} is: ", np.mean(arr[i]))
    print(f"Sum for row {i} is: ", np.sum(arr[i]))
    print(f"Max of row {i} is: ", np.max(arr[i]))
    print(f"Min of row {i} is: ", np.min(arr[i]))

for i in range (len(arr)):
    print(f"Mean for column {i} is: ", np.mean(arr[:,i]))
    print(f"Sum for column {i} is: ", np.sum(arr[:,i]))
    print(f"Max of column {i} is: ", np.max(arr[:,i]))
    print(f"Min of column {i} is: ", np.min(arr[:,i]))

Random array:  [[10 48 12 25 21]
 [29  2 48 35  8]
 [25  8  4 44 50]
 [ 6 43 26 25 19]
 [ 2 41 42  3 40]]
Mean for row 0 is:  23.2
Sum for row 0 is:  116
Max of row 0 is:  48
Min of row 0 is:  10
Mean for row 1 is:  24.4
Sum for row 1 is:  122
Max of row 1 is:  48
Min of row 1 is:  2
Mean for row 2 is:  26.2
Sum for row 2 is:  131
Max of row 2 is:  50
Min of row 2 is:  4
Mean for row 3 is:  23.8
Sum for row 3 is:  119
Max of row 3 is:  43
Min of row 3 is:  6
Mean for row 4 is:  25.6
Sum for row 4 is:  128
Max of row 4 is:  42
Min of row 4 is:  2
Mean for column 0 is:  14.4
Sum for column 0 is:  72
Max of column 0 is:  29
Min of column 0 is:  2
Mean for column 1 is:  28.4
Sum for column 1 is:  142
Max of column 1 is:  48
Min of column 1 is:  2
Mean for column 2 is:  26.4
Sum for column 2 is:  132
Max of column 2 is:  48
Min of column 2 is:  4
Mean for column 3 is:  26.4
Sum for column 3 is:  132
Max of column 3 is:  44
Min of column 3 is:  3
Mean for column 4 is:  27.6
Sum for column 4 

In [81]:
#task3
arr = np.eye(5,5)

for i in range (len(arr)):
    for j in range (len(arr)):
        if i==j:
            arr[i,j] += 5
arr[4,:] = 1
arr

array([[6., 0., 0., 0., 0.],
       [0., 6., 0., 0., 0.],
       [0., 0., 6., 0., 0.],
       [0., 0., 0., 6., 0.],
       [1., 1., 1., 1., 1.]])

In [76]:
#task4
arr = np.random.randint(low=0, high=20, size=15)
hashset = {}
print(arr)
for element in arr:
    if element in hashset:
        hashset[element] += 1
    else:
        hashset[element] = 1      
for count in hashset:
    print(f"Element {count} has count: ", hashset[count])
for i in range (len(arr)):
    if arr[i] > 10:
        print(i)

[ 8 10 19 11 16  2 17 10 13  9  9  0  7  4  3]
Element 8 has count:  1
Element 10 has count:  2
Element 19 has count:  1
Element 11 has count:  1
Element 16 has count:  1
Element 2 has count:  1
Element 17 has count:  1
Element 13 has count:  1
Element 9 has count:  2
Element 0 has count:  1
Element 7 has count:  1
Element 4 has count:  1
Element 3 has count:  1
2
3
4
6
8


In [93]:
#task5
arr = np.random.rand(3,4)
new = arr.round(2)
new[:,1] = 0.5
new

array([[0.98, 0.5 , 0.73, 0.13],
       [0.22, 0.5 , 0.6 , 0.54],
       [0.15, 0.5 , 0.99, 0.16]])