# **Lab 2**

## **Task 1**

In [59]:
import numpy as np

weights = np.random.randint(60,90,size=20)
heights = np.random.randint(5,7,size=20)
points = np.random.randint(30,100,size=20)

stats = np.column_stack((weights, heights, points))
max_player  = np.argmax(stats[:,2])
stats[max_player, 0] = 50
update_stat = np.vstack((stats, [85,6,90]))
insert_stat = np.insert(stats, 7, 55, axis=0)
min_player  = np.argmin(stats[:,2])
delete = np.delete(stats, [min_player,1])
stats

array([[82,  5, 32],
       [67,  5, 33],
       [73,  5, 75],
       [71,  6, 61],
       [73,  5, 55],
       [81,  6, 62],
       [50,  6, 99],
       [79,  6, 94],
       [87,  6, 42],
       [82,  6, 99],
       [82,  5, 65],
       [81,  5, 31],
       [69,  6, 40],
       [69,  6, 48],
       [61,  6, 55],
       [76,  6, 97],
       [71,  5, 60],
       [87,  5, 71],
       [71,  5, 54],
       [65,  5, 80]])

## **Task 2**

In [60]:
import numpy as np

purchase_amounts = np.random.randint(low=100,high=1000, size=(20,))
item_counts = np.random.randint(low=1, high = 100, size=(20,))

shallow_copy = purchase_amounts[::]
deep_copy = item_counts.copy()

conc = np.concatenate((purchase_amounts, item_counts) , axis=0)

split = item_counts[item_counts > 50]
print(split)

purchase_amounts[19] = -1
item_counts[0] = -1
purchase_amounts, shallow_copy, item_counts, deep_copy

[79 97 71 93 81 69 69 67]


(array([952, 306, 923, 429, 658, 161, 686, 657, 803, 954, 797, 652, 742,
        916, 916, 777, 793, 252, 427,  -1]),
 array([952, 306, 923, 429, 658, 161, 686, 657, 803, 954, 797, 652, 742,
        916, 916, 777, 793, 252, 427,  -1]),
 array([-1, 12, 79, 97, 71, 16, 93, 81, 69,  8, 47, 34, 26, 22, 49, 27, 12,
        69, 15, 67]),
 array([27, 12, 79, 97, 71, 16, 93, 81, 69,  8, 47, 34, 26, 22, 49, 27, 12,
        69, 15, 67]))